# typed: false
# frozen_string_literal: true

# This file is generated by the tyto-cli release workflow. DO NOT EDIT.
class Tyto < Formula
  desc "Command-line interface for the Tyto Compute API"
  homepage "https://tyto.run"
  version "0.2.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://get.tyto.run/releases/v0.2.16/tyto-darwin-amd64", using: :nounzip
      sha256 "c62708adbe455190e37a50c48b6b83320db51226f5e7c68acf420b9745102b9d"

      def install
        bin.install "tyto-darwin-amd64" => "tyto"
        chmod 0755, bin/"tyto"
      end
    end
    if Hardware::CPU.arm?
      url "https://get.tyto.run/releases/v0.2.16/tyto-darwin-arm64", using: :nounzip
      sha256 "74d46282b94fe83724482b37b623d061b0f110b30d9b673b479ae29d92f28752"

      def install
        bin.install "tyto-darwin-arm64" => "tyto"
        chmod 0755, bin/"tyto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://get.tyto.run/releases/v0.2.16/tyto-linux-amd64", using: :nounzip
      sha256 "98c86d53a5c47b99c50264467d56c5ebf9bb3a188ec128ebd02614dd55eeb7b8"

      def install
        bin.install "tyto-linux-amd64" => "tyto"
        chmod 0755, bin/"tyto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.tyto.run/releases/v0.2.16/tyto-linux-arm64", using: :nounzip
      sha256 "f41fbb07daa740beb90d5912e5a688a9f9841d1fba2c912c9886dcec4acb0a68"

      def install
        bin.install "tyto-linux-arm64" => "tyto"
        chmod 0755, bin/"tyto"
      end
    end
  end

  livecheck do
    url "https://get.tyto.run/releases/latest"
    regex(/v?(\d+(?:\.\d+)+)/i)
  end

  test do
    assert_match "tyto version v#{version}", shell_output("#{bin}/tyto version")
  end
end
