# typed: false
# frozen_string_literal: true

# This file is generated by the tyto-cli release workflow. DO NOT EDIT.
class Tyto < Formula
  desc "Command-line interface for the Tyto Compute API"
  homepage "https://tyto.run"
  version "0.2.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://get.tyto.run/releases/v0.2.12/tyto-darwin-amd64", using: :nounzip
      sha256 "3f13119df5e718c66a8e016a3eb3ba6fc97c7e8959dcbee2470b71622954b925"

      def install
        bin.install "tyto-darwin-amd64" => "tyto"
        chmod 0755, bin/"tyto"
      end
    end
    if Hardware::CPU.arm?
      url "https://get.tyto.run/releases/v0.2.12/tyto-darwin-arm64", using: :nounzip
      sha256 "be27ce55b0b00e2e38f33c16bf53905c8cfee9105f5bcd3ebb4b8a4d4b4eaeb7"

      def install
        bin.install "tyto-darwin-arm64" => "tyto"
        chmod 0755, bin/"tyto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://get.tyto.run/releases/v0.2.12/tyto-linux-amd64", using: :nounzip
      sha256 "500471dc5c5ac067382e92b0c7c4d07f2664923e6721e71d5af6780d019e6d9d"

      def install
        bin.install "tyto-linux-amd64" => "tyto"
        chmod 0755, bin/"tyto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.tyto.run/releases/v0.2.12/tyto-linux-arm64", using: :nounzip
      sha256 "a543604d782ccf718ce1ccbf83e67115447a58cfab3adeed194bdbd1cc5f1e55"

      def install
        bin.install "tyto-linux-arm64" => "tyto"
        chmod 0755, bin/"tyto"
      end
    end
  end

  livecheck do
    url "https://get.tyto.run/releases/latest"
    regex(/v?(\d+(?:\.\d+)+)/i)
  end

  test do
    assert_match "tyto version v#{version}", shell_output("#{bin}/tyto version")
  end
end
