# typed: false
# frozen_string_literal: true

# This file is generated by the tyto-cli release workflow. DO NOT EDIT.
class Tyto < Formula
  desc "Command-line interface for the Tyto Compute API"
  homepage "https://tyto.run"
  version "0.2.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://get.tyto.run/releases/v0.2.10/tyto-darwin-amd64", using: :nounzip
      sha256 "b5d3c3e025f10ec1a1d684e277a8148baa2077808c6c68221ac1ecf39e86bcbf"

      def install
        bin.install "tyto-darwin-amd64" => "tyto"
        chmod 0755, bin/"tyto"
      end
    end
    if Hardware::CPU.arm?
      url "https://get.tyto.run/releases/v0.2.10/tyto-darwin-arm64", using: :nounzip
      sha256 "154c317e25a650e1790e053598f91c2c5f7718ed9324c5ee4eaf9d08350c68b9"

      def install
        bin.install "tyto-darwin-arm64" => "tyto"
        chmod 0755, bin/"tyto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://get.tyto.run/releases/v0.2.10/tyto-linux-amd64", using: :nounzip
      sha256 "c81ea3c47fa3c8224f45e2b53d6dd8a55d5b6a0afeca95608929c24d1d61414b"

      def install
        bin.install "tyto-linux-amd64" => "tyto"
        chmod 0755, bin/"tyto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.tyto.run/releases/v0.2.10/tyto-linux-arm64", using: :nounzip
      sha256 "aff6411aa912db8052f1c63123e7626d1e40fbb4e19dcd6ada8441bfe06a8a7d"

      def install
        bin.install "tyto-linux-arm64" => "tyto"
        chmod 0755, bin/"tyto"
      end
    end
  end

  livecheck do
    url "https://get.tyto.run/releases/latest"
    regex(/v?(\d+(?:\.\d+)+)/i)
  end

  test do
    assert_match "tyto version v#{version}", shell_output("#{bin}/tyto version")
  end
end
